#!/usr/bin/env bash
# (init) script 101-manage_my_process that manages manage_my_process
pidFile="/var/run/my_process.pid"

start()
{
	./manage_my_process &
	echo "$!" > $pidFile
}

stop()
{
	kill "$(cat $pidFile)"
	rm $pidFile
}

restart()
{
	stop
	start
}

if [ $# -ne 1 ]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi

case "$1" in
	start)
		start
		echo "manage_my_process started"
		;;
	stop)
		stop
		echo "manage_my_process stopped"
		;;
	restart)
		restart
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit
esac
